kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: suleimant/docker-obs-ndi
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - latest
